name: Pull Request Action
description: Automate pull requests with GitHub Actions
author: Ian Walter
branding:
  icon: book
  color: blue
inputs:
  title:
    description: Pull request title
    required: true
  body:
    description: Pull request body
    required: false
  head:
    description: Pull request head branch
    required: false
  base:
    description: Pull request base branch
    required: false
  commit:
    description: Commit changes
    required: false
  files:
    description: Files to commit
    required: false
  message:
    description: Commit message
    required: false
  actor:
    description: Commit author
    required: false
  token:
    description: GitHub token
    required: false
runs:
  using: docker
  image: Dockerfile
