name: Pull Request Action
description: Automate pull requests with GitHub Actions
author: Ian Walter
branding:
  icon: book
  color: blue
inputs:
  title:
    description: The title of the pull request you want to create.
    required: true
  head:
    description: The branch for the pull request you want to create.
    required: false
  base:
    description: The branch you want to point the pull request to.
    required: false
  files:
    description: The changed files you want included in the commit.
    required: false
  message:
    description: The commit message.
    required: false
  actor:
    description: Who to author the commit as.
    required: false
  token:
    description: The GitHub token to use to push the commit to GitHub.
    required: false
runs:
  using: docker
  image: Dockerfile
