name: PR
on:
  workflow_dispatch:
    inputs:
      title:
        description: The title of the pull request you want to create.
        required: true
      body:
        description: The body of the pull request comment/description.
        required: false
      head:
        description: The branch for the pull request you want to create.
        required: false
      base:
        description: The branch you want to point the pull request to.
        required: false
      commit:
        description: |
          Whether to automatically stage and commit changed files before
          creating the pull request.
        required: false
      files:
        description: The changed files you want included in the commit.
        required: false
      message:
        description: The commit message.
        required: false
      actor:
        description: Who to author the commit as.
        required: false
      token:
        description: The GitHub token to use to push the commit to GitHub.
        required: false
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      DEBUG: pull-request-action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
      - name: Make Change
        run: echo "Racks 2 Skinny" > commits/$(date +%s).txt
      - name: Create pull request
        uses: ./
        with:
          token: ${{ secrets.GH_PAT }}
          title: ${{ github.event.inputs.title }}
          commit: ${{ github.event.inputs.commit }}

