name: PR
on:
  workflow_dispatch:
    inputs:
      title:
        description: Pull request title
        required: true
      body:
        description: Pull request body
        required: false
      head:
        description: Pull request head branch
        required: false
      base:
        description: Pull request base branch
        required: false
      commit:
        description: Commit changes
        required: false
      files:
        description: Files to commit
        required: false
      message:
        description: Commit message
        required: false
      actor:
        description: Commit author
        required: false
      token:
        description: GitHub token
        required: false
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      DEBUG: pull-request-action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
      - name: Make Change
        run: echo "Racks 2 Skinny" > commits/$(date +%s).txt
      - name: Create pull request
        uses: ./
        with:
          token: ${{ secrets.GH_PAT }}
          title: ${{ github.event.inputs.title }}
          commit: ${{ github.event.inputs.commit }}

